<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>DocTest (Ruby)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^=begin</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ruby</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>multiline comments</string>
			<key>end</key>
			<string>^=end</string>
			<key>name</key>
			<string>comment.block.documentation.ruby</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>text.ruby.doctest</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([ \t]*(#)\s+)(doctest:)(.*)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.ruby.doctest</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.ruby.doctest</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^(?=\1[^\s])|^(?=\1$)</string>
			<key>name</key>
			<string>source.ruby.doctest.description.commented</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#indented_description</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([ \t]*(#)\s+)(&gt;&gt;|=&gt;|doctest_require:)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.ruby.doctest</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^(?=\1[^\s])|^(?=\1$)</string>
			<key>name</key>
			<string>source.ruby.doctest.statement.commented</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([ \t]*(#)\s+)(\!\!\!)\s*$</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.number-sign.ruby</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.ruby.doctest</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>source.ruby.doctest.directive</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.ruby</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>indented_description</key>
		<dict>
			<key>begin</key>
			<string>^([ \t]*#\s+)(.+)</string>
			<key>end</key>
			<string>^(?!\1)</string>
			<key>name</key>
			<string>comment.ruby.doctest</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ruby.doctest</string>
	<key>uuid</key>
	<string>24D55BB8-4A63-43A7-92EE-D778D6893B62</string>
</dict>
</plist>
