<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
		<string>text</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~R</string>
	<key>name</key>
	<string>DocTest (Text)</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>^(doctest:)(.*)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ruby.doctest</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.ruby.doctest</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=[^\s]|$)</string>
			<key>name</key>
			<string>source.ruby.doctest.description.unindented</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#indented_description</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s+)(doctest:)(.*)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.ruby.doctest</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.ruby.doctest</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^(?=\1[^\s])|^(?=\1$)</string>
			<key>name</key>
			<string>source.ruby.doctest.description.indented</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#indented_description</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(&gt;&gt;|=&gt;|doctest_require:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.ruby.doctest</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?=[^\s]|$)</string>
			<key>name</key>
			<string>source.ruby.doctest.statement.unindented</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s+)(&gt;&gt;|=&gt;|doctest_require:)</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.ruby.doctest</string>
				</dict>
			</dict>
			<key>end</key>
			<string>^(?!\1)|^(?=\1[^\s])|^(?=\1$)</string>
			<key>name</key>
			<string>source.ruby.doctest.statement.indented</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.ruby.rails</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(\s*)(\!\!\!)\s*$</string>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.ruby.doctest</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>source.ruby.doctest.directive</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>indented_description</key>
		<dict>
			<key>begin</key>
			<string>^(\s+)(.+)</string>
			<key>end</key>
			<string>^(?!\1)</string>
			<key>name</key>
			<string>comment.ruby.doctest</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.ruby.doctest</string>
	<key>uuid</key>
	<string>68EA33DD-082C-405A-ACD2-2CD6923CAE53</string>
</dict>
</plist>
